import 'dart:convert';

import 'models.dart';

class MetaException implements Exception {
  MetaException(this.errorKey, [this.detail]);

  final String errorKey;
  final String? detail;

  @override
  String toString() => detail == null ? errorKey : '$errorKey: $detail';
}

class MetaAnalysis {
  const MetaAnalysis({
    required this.titleLength,
    required this.titleStatus,
    required this.descriptionLength,
    required this.descriptionStatus,
    required this.ogComplete,
    required this.twitterComplete,
    required this.warnings,
    required this.tips,
  });

  final int titleLength;
  final SeoLengthStatus titleStatus;
  final int descriptionLength;
  final SeoLengthStatus descriptionStatus;
  final bool ogComplete;
  final bool twitterComplete;
  final List<String> warnings;
  final List<String> tips;
}

enum SeoLengthStatus { tooShort, optimal, tooLong }

class MetaEngine {
  MetaEngine._();

  static const int titleMin = 30;
  static const int titleMax = 60;
  static const int descriptionMin = 120;
  static const int descriptionMax = 160;

  static String build(MetaConfig c) {
    final StringBuffer b = StringBuffer();
    b.writeln('<!-- Generated by MiniTools — SEO Pack -->');

    _line(b, 'title', c.title);

    if (c.language.trim().isNotEmpty) {
      b.writeln('<html lang="${_esc(c.language.trim())}">');
    }

    _meta(b, 'charset', 'UTF-8', useContentAttr: false);
    _meta(b, 'viewport', c.viewport);
    _meta(b, 'description', c.description);
    _meta(b, 'keywords', c.keywords);
    _meta(b, 'author', c.author);
    _meta(b, 'robots', c.robotsContent);

    if (c.themeColor.trim().isNotEmpty) {
      _meta(b, 'theme-color', c.themeColor.trim());
    }

    if (c.canonical.trim().isNotEmpty) {
      b.writeln('<link rel="canonical" href="${_esc(c.canonical.trim())}">');
    }

    if (c.faviconEnabled) {
      b.writeln();
      b.writeln('<!-- Favicons -->');
      if (c.faviconIco.trim().isNotEmpty) {
        b.writeln('<link rel="icon" href="${_esc(c.faviconIco.trim())}" sizes="any">');
      }
      if (c.iconSvg.trim().isNotEmpty) {
        b.writeln('<link rel="icon" href="${_esc(c.iconSvg.trim())}" type="image/svg+xml">');
      }
      if (c.icon32.trim().isNotEmpty) {
        b.writeln('<link rel="icon" href="${_esc(c.icon32.trim())}" sizes="32x32" type="image/png">');
      }
      if (c.icon16.trim().isNotEmpty) {
        b.writeln('<link rel="icon" href="${_esc(c.icon16.trim())}" sizes="16x16" type="image/png">');
      }
      if (c.appleTouchIcon.trim().isNotEmpty) {
        b.writeln('<link rel="apple-touch-icon" href="${_esc(c.appleTouchIcon.trim())}">');
      }
      if (c.manifest.trim().isNotEmpty) {
        b.writeln('<link rel="manifest" href="${_esc(c.manifest.trim())}">');
      }
    }

    if (c.ogEnabled) {
      b.writeln();
      b.writeln('<!-- Open Graph -->');
      _property(b, 'og:type', c.ogType.value);
      _property(b, 'og:title', _fallback(c.ogTitle, c.title));
      _property(b, 'og:description', _fallback(c.ogDescription, c.description));
      _property(b, 'og:image', c.ogImage);
      _property(b, 'og:url', _fallback(c.ogUrl, c.canonical));
      _property(b, 'og:site_name', c.ogSiteName);
      _property(b, 'og:locale', c.ogLocale);
    }

    if (c.twitterEnabled) {
      b.writeln();
      b.writeln('<!-- Twitter Card -->');
      _name(b, 'twitter:card', c.twitterCard.value);
      _name(b, 'twitter:title', _fallback(c.twitterTitle, c.title));
      _name(b, 'twitter:description',
          _fallback(c.twitterDescription, c.description));
      _name(b, 'twitter:image', _fallback(c.twitterImage, c.ogImage));
      _name(b, 'twitter:site', c.twitterSite);
      _name(b, 'twitter:creator', c.twitterCreator);
    }

    b.write('</head>');
    return b.toString();
  }

  static void _line(StringBuffer b, String tag, String value) {
    if (value.trim().isEmpty) return;
    b.writeln('<$tag>${_esc(value.trim())}</$tag>');
  }

  static void _meta(
      StringBuffer b,
      String name,
      String value, {
        bool useContentAttr = true,
      }) {
    if (value.trim().isEmpty) return;
    if (useContentAttr) {
      b.writeln('<meta name="${_esc(name)}" content="${_esc(value.trim())}">');
    } else {
      b.writeln('<meta ${_esc(name)}="${_esc(value.trim())}">');
    }
  }

  static void _property(StringBuffer b, String property, String value) {
    if (value.trim().isEmpty) return;
    b.writeln(
      '<meta property="${_esc(property)}" content="${_esc(value.trim())}">',
    );
  }

  static void _name(StringBuffer b, String name, String value) {
    if (value.trim().isEmpty) return;
    b.writeln('<meta name="${_esc(name)}" content="${_esc(value.trim())}">');
  }

  static String _fallback(String primary, String fallback) {
    final String p = primary.trim();
    if (p.isNotEmpty) return p;
    return fallback.trim();
  }

  static String _esc(String input) {
    return input
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;');
  }

  // ==========================================================================
  // ANALYSIS
  // ==========================================================================

  static MetaAnalysis analyze(MetaConfig c) {
    final int titleLen = c.title.trim().runes.length;
    final int descLen = c.description.trim().runes.length;

    final SeoLengthStatus titleStatus = _statusFor(
      titleLen,
      titleMin,
      titleMax,
    );
    final SeoLengthStatus descStatus = _statusFor(
      descLen,
      descriptionMin,
      descriptionMax,
    );

    final bool ogComplete = !c.ogEnabled ||
        (c.ogImage.trim().isNotEmpty &&
            _fallback(c.ogTitle, c.title).isNotEmpty &&
            _fallback(c.ogDescription, c.description).isNotEmpty);

    final bool twitterComplete = !c.twitterEnabled ||
        (c.twitterSite.trim().isNotEmpty &&
            _fallback(c.twitterImage, c.ogImage).isNotEmpty);

    final List<String> warnings = <String>[];
    final List<String> tips = <String>[];

    if (c.title.trim().isEmpty) {
      warnings.add('Missing <title> tag.');
    } else if (titleLen > titleMax) {
      warnings.add('Title is $titleLen chars — likely to be truncated in search results.');
    } else if (titleLen < titleMin) {
      tips.add('Title is short ($titleLen chars). Add descriptive words.');
    }

    if (c.description.trim().isEmpty) {
      warnings.add('Missing meta description — search engines will generate one.');
    } else if (descLen > descriptionMax) {
      warnings.add('Description is $descLen chars — may be truncated at ~$descriptionMax.');
    } else if (descLen < descriptionMin) {
      tips.add('Description is short ($descLen chars). Aim for $descriptionMin–$descriptionMax.');
    }

    if (c.canonical.trim().isEmpty) {
      tips.add('Add a canonical URL to prevent duplicate-content issues.');
    }
    if (c.ogEnabled && c.ogImage.trim().isEmpty) {
      warnings.add('Open Graph enabled but og:image is missing.');
    }
    if (c.twitterEnabled && c.twitterSite.trim().isEmpty) {
      tips.add('Add twitter:site (@handle) for attribution.');
    }
    if (c.robotsIndex == false && c.robotsFollow == false) {
      warnings.add('Page is set to noindex, nofollow — it will be excluded from search engines.');
    }
    if (c.viewport.trim().isEmpty) {
      warnings.add('Missing viewport meta — mobile rendering will be broken.');
    }

    return MetaAnalysis(
      titleLength: titleLen,
      titleStatus: titleStatus,
      descriptionLength: descLen,
      descriptionStatus: descStatus,
      ogComplete: ogComplete,
      twitterComplete: twitterComplete,
      warnings: warnings,
      tips: tips,
    );
  }

  static SeoLengthStatus _statusFor(int length, int min, int max) {
    if (length < min) return SeoLengthStatus.tooShort;
    if (length > max) return SeoLengthStatus.tooLong;
    return SeoLengthStatus.optimal;
  }

  static String buildRobotsTxt({
    String userAgent = '*',
    bool allowAll = true,
    List<String> disallow = const <String>[],
    List<String> allow = const <String>[],
    String? sitemapUrl,
    String? host,
  }) {
    final StringBuffer b = StringBuffer();
    b.writeln('User-agent: $userAgent');
    if (allowAll && disallow.isEmpty) {
      b.writeln('Allow: /');
    } else {
      for (final String a in allow) {
        if (a.trim().isEmpty) continue;
        b.writeln('Allow: ${a.trim()}');
      }
      for (final String d in disallow) {
        if (d.trim().isEmpty) continue;
        b.writeln('Disallow: ${d.trim()}');
      }
    }
    if (host != null && host.trim().isNotEmpty) {
      b.writeln();
      b.writeln('Host: ${host.trim()}');
    }
    if (sitemapUrl != null && sitemapUrl.trim().isNotEmpty) {
      b.writeln();
      b.writeln('Sitemap: ${sitemapUrl.trim()}');
    }
    return b.toString().trimRight();
  }

  static String jsonExport(MetaConfig c) {
    final Map<String, dynamic> out = <String, dynamic>{
      'title': c.title,
      'description': c.description,
      'keywords': c.keywords,
      'author': c.author,
      'canonical': c.canonical,
      'language': c.language,
      'viewport': c.viewport,
      'themeColor': c.themeColor,
      'robots': c.robotsContent,
      if (c.ogEnabled) 'openGraph': <String, dynamic>{
        'type': c.ogType.value,
        'title': _fallback(c.ogTitle, c.title),
        'description': _fallback(c.ogDescription, c.description),
        'image': c.ogImage,
        'url': _fallback(c.ogUrl, c.canonical),
        'siteName': c.ogSiteName,
        'locale': c.ogLocale,
      },
      if (c.twitterEnabled) 'twitter': <String, dynamic>{
        'card': c.twitterCard.value,
        'title': _fallback(c.twitterTitle, c.title),
        'description': _fallback(c.twitterDescription, c.description),
        'image': _fallback(c.twitterImage, c.ogImage),
        'site': c.twitterSite,
        'creator': c.twitterCreator,
      },
    };
    return const JsonEncoder.withIndent('  ').convert(out);
  }
}