import 'dart:convert';

import 'models.dart';

class RedirectException implements Exception {
  RedirectException(this.errorKey, [this.detail]);

  final String errorKey;
  final String? detail;

  @override
  String toString() => detail == null ? errorKey : '$errorKey: $detail';
}

class RedirectEngine {
  RedirectEngine._();

  static final RegExp _pathRegex = RegExp(r'^[/a-zA-Z0-9_\-.*?=&%:#+~@!$(),;\[\]]+$');
  static final RegExp _urlRegex = RegExp(
    r'^(https?://|/)[^\s]*$',
    caseSensitive: false,
  );

  static String build(RedirectConfig config) {
    if (config.rules.isEmpty) {
      throw RedirectException(SeoErrors.redirectEmpty);
    }

    for (int i = 0; i < config.rules.length; i++) {
      _validateRule(config.rules[i], i);
    }

    switch (config.format) {
      case RedirectFormat.htaccess:
        return _buildHtaccess(config);
      case RedirectFormat.nginx:
        return _buildNginx(config);
      case RedirectFormat.netlify:
        return _buildNetlify(config);
      case RedirectFormat.vercel:
        return _buildVercel(config);
      case RedirectFormat.cloudflare:
        return _buildCloudflare(config);
    }
  }

  static void _validateRule(RedirectRule r, int index) {
    final String from = r.from.trim();
    final String to = r.to.trim();

    if (from.isEmpty) {
      throw RedirectException(
        SeoErrors.redirectInvalidFrom,
        'Rule #${index + 1}: source is empty',
      );
    }
    if (to.isEmpty) {
      throw RedirectException(
        SeoErrors.redirectInvalidTo,
        'Rule #${index + 1}: target is empty',
      );
    }
    if (from.contains(' ') && !from.startsWith('http')) {
      throw RedirectException(
        SeoErrors.redirectInvalidFrom,
        'Rule #${index + 1}: source cannot contain spaces',
      );
    }
    if (!_urlRegex.hasMatch(from) && !_pathRegex.hasMatch(from)) {
      throw RedirectException(
        SeoErrors.redirectInvalidFrom,
        'Rule #${index + 1}: invalid source pattern',
      );
    }
  }

  // ==========================================================================
  // APACHE .htaccess
  // ==========================================================================

  static String _buildHtaccess(RedirectConfig config) {
    final StringBuffer b = StringBuffer();
    b.writeln('# Generated by MiniTools — SEO Pack');
    b.writeln('# https://example.com');
    b.writeln();

    final bool hasHttps = config.rules.any((RedirectRule r) => r.forceHttps);
    final bool hasWwwRemoval =
    config.rules.any((RedirectRule r) => r.removeWww);
    final bool hasWwwAdd = config.rules.any((RedirectRule r) => r.addWww);

    if (hasHttps || hasWwwRemoval || hasWwwAdd) {
      b.writeln('<IfModule mod_rewrite.c>');
      b.writeln('RewriteEngine On');
      b.writeln();

      if (hasHttps) {
        b.writeln('# Force HTTPS');
        b.writeln('RewriteCond %{HTTPS} off');
        b.writeln('RewriteRule ^(.*)\$ https://%{HTTP_HOST}/\$1 [R=301,L]');
        b.writeln();
      }

      if (hasWwwRemoval) {
        b.writeln('# Remove www');
        b.writeln('RewriteCond %{HTTP_HOST} ^www\\.(.+)\$ [NC]');
        b.writeln('RewriteRule ^(.*)\$ https://%1/\$1 [R=301,L]');
        b.writeln();
      }

      if (hasWwwAdd) {
        b.writeln('# Add www');
        b.writeln('RewriteCond %{HTTP_HOST} !^www\\. [NC]');
        b.writeln('RewriteRule ^(.*)\$ https://www.%{HTTP_HOST}/\$1 [R=301,L]');
        b.writeln();
      }

      b.writeln('</IfModule>');
      b.writeln();
    }

    b.writeln('<IfModule mod_alias.c>');
    b.writeln();

    for (final RedirectRule r in config.rules) {
      if (r.forceHttps || r.removeWww || r.addWww) continue;

      final int code = r.status.code;
      final String from = _normalizeFrom(r.from);
      final String to = _normalizeTo(r.to);

      b.writeln('# ${_humanRule(r)}');
      if (_containsWildcard(from)) {
        final String regex = _wildcardToRegex(from);
        b.writeln('RedirectMatch $code $regex $to');
      } else {
        b.writeln('Redirect $code $from $to');
      }
      b.writeln();
    }

    b.writeln('</IfModule>');
    return b.toString().trimRight();
  }

  static bool _containsWildcard(String s) => s.contains('*') || s.contains('?');

  static String _wildcardToRegex(String pattern) {
    final String escaped = pattern
        .replaceAllMapped(RegExp(r'[.+^${}()|\[\]\\]'), (Match m) => '\\${m.group(0)}')
        .replaceAll('*', '.*')
        .replaceAll('?', '.');
    return '^$escaped\$';
  }

  // ==========================================================================
  // NGINX
  // ==========================================================================

  static String _buildNginx(RedirectConfig config) {
    final StringBuffer b = StringBuffer();
    b.writeln('# Generated by MiniTools — SEO Pack');
    b.writeln('# Place inside your server { } block');
    b.writeln();

    for (final RedirectRule r in config.rules) {
      b.writeln('# ${_humanRule(r)}');

      if (r.forceHttps) {
        b.writeln('if (\$scheme != "https") {');
        b.writeln('    return 301 https://\$host\$request_uri;');
        b.writeln('}');
        b.writeln();
        continue;
      }

      if (r.removeWww) {
        b.writeln('if (\$host ~* ^www\\.(.+)\$) {');
        b.writeln('    return 301 https://\$1\$request_uri;');
        b.writeln('}');
        b.writeln();
        continue;
      }

      if (r.addWww) {
        b.writeln('if (\$host !~* ^www\\.) {');
        b.writeln('    return 301 https://www.\$host\$request_uri;');
        b.writeln('}');
        b.writeln();
        continue;
      }

      final String from = _normalizeFrom(r.from);
      final String to = _normalizeTo(r.to);
      final int code = r.status.code;

      if (_containsWildcard(from)) {
        final String regex = _wildcardToRegex(from).replaceAll('^', '').replaceAll(r'$', '');
        b.writeln('location ~ ^$regex\$ {');
        if (r.preserveQuery) {
          b.writeln('    return $code $to\$is_args\$args;');
        } else {
          b.writeln('    return $code $to;');
        }
        b.writeln('}');
      } else {
        b.writeln('location = $from {');
        if (r.preserveQuery) {
          b.writeln('    return $code $to\$is_args\$args;');
        } else {
          b.writeln('    return $code $to;');
        }
        b.writeln('}');
      }
      b.writeln();
    }

    return b.toString().trimRight();
  }

  // ==========================================================================
  // NETLIFY _redirects
  // ==========================================================================

  static String _buildNetlify(RedirectConfig config) {
    final StringBuffer b = StringBuffer();
    b.writeln('# Generated by MiniTools — SEO Pack');
    b.writeln('# https://docs.netlify.com/routing/redirects/');
    b.writeln();

    for (final RedirectRule r in config.rules) {
      b.writeln('# ${_humanRule(r)}');
      b.write(_netlifyLine(r, includeQuery: r.preserveQuery));
      b.writeln();
    }

    return b.toString().trimRight();
  }

  static String _buildCloudflare(RedirectConfig config) {
    final StringBuffer b = StringBuffer();
    b.writeln('# Generated by MiniTools — SEO Pack');
    b.writeln('# Cloudflare Pages _redirects');
    b.writeln();

    for (final RedirectRule r in config.rules) {
      b.writeln('# ${_humanRule(r)}');
      b.write(_netlifyLine(r, includeQuery: r.preserveQuery, force: true));
      b.writeln();
    }

    return b.toString().trimRight();
  }

  static String _netlifyLine(
      RedirectRule r, {
        required bool includeQuery,
        bool force = false,
      }) {
    final String from = _normalizeFrom(r.from);
    final String to = _normalizeTo(r.to);
    final int code = r.status.code;

    final StringBuffer line = StringBuffer();
    line.write(from);
    line.write('  ');
    line.write(to);
    line.write('  ');
    line.write(code);
    if (force) line.write('!');
    if (includeQuery && !to.contains('?')) {
      line.write('  # query string is preserved automatically');
    }
    return line.toString();
  }

  // ==========================================================================
  // VERCEL vercel.json
  // ==========================================================================

  static String _buildVercel(RedirectConfig config) {
    final List<Map<String, dynamic>> redirects = <Map<String, dynamic>>[];

    for (final RedirectRule r in config.rules) {
      if (r.forceHttps) {
        redirects.add(<String, dynamic>{
          'source': '/(.*)',
          'has': <Map<String, String>>[
            <String, String>{'type': 'header', 'key': 'x-forwarded-proto', 'value': 'http'},
          ],
          'destination': 'https://\$1',
          'permanent': true,
        });
        continue;
      }
      if (r.removeWww) {
        redirects.add(<String, dynamic>{
          'source': '/(.*)',
          'has': <Map<String, String>>[
            <String, String>{'type': 'host', 'value': 'www.example.com'},
          ],
          'destination': 'https://example.com/\$1',
          'permanent': true,
        });
        continue;
      }
      if (r.addWww) {
        redirects.add(<String, dynamic>{
          'source': '/(.*)',
          'destination': 'https://www.\$host/\$1',
          'permanent': true,
        });
        continue;
      }

      redirects.add(<String, dynamic>{
        'source': _normalizeFrom(r.from),
        'destination': _normalizeTo(r.to),
        'permanent': _isPermanent(r.status),
      });
    }

    final Map<String, dynamic> root = <String, dynamic>{
      'redirects': redirects,
    };

    return const JsonEncoder.withIndent('  ').convert(root);
  }

  // ==========================================================================
  // HELPERS
  // ==========================================================================

  static bool _isPermanent(RedirectStatus s) {
    return s == RedirectStatus.s301 || s == RedirectStatus.s308;
  }

  static String _normalizeFrom(String s) {
    String t = s.trim();
    if (t.startsWith('http://') || t.startsWith('https://')) {
      final Uri? uri = Uri.tryParse(t);
      if (uri != null) {
        t = uri.path.isEmpty ? '/' : uri.path;
      }
    }
    if (!t.startsWith('/') && !t.startsWith('^')) {
      t = '/$t';
    }
    return t;
  }

  static String _normalizeTo(String s) {
    String t = s.trim();
    if (t == '/' || t.startsWith('http://') || t.startsWith('https://')) {
      return t;
    }
    if (!t.startsWith('/') && !t.startsWith(r'$')) {
      t = '/$t';
    }
    return t;
  }

  static String _humanRule(RedirectRule r) {
    if (r.forceHttps) return 'Force HTTPS';
    if (r.removeWww) return 'Remove www prefix';
    if (r.addWww) return 'Add www prefix';
    return '${_normalizeFrom(r.from)} → ${_normalizeTo(r.to)} (${r.status.code})';
  }

  static String inferFormatFilename(RedirectFormat f) => f.filename;

  static String describeStatus(RedirectStatus s) {
    switch (s) {
      case RedirectStatus.s301:
        return 'Permanent. Search engines transfer ranking to the new URL.';
      case RedirectStatus.s302:
        return 'Temporary. Ranking stays on the old URL.';
      case RedirectStatus.s303:
        return 'See Other. Forces GET on the new URL.';
      case RedirectStatus.s307:
        return 'Temporary. Preserves the HTTP method.';
      case RedirectStatus.s308:
        return 'Permanent. Preserves the HTTP method.';
    }
  }
}