import 'models.dart';

class DdlGenerator {
  DdlGenerator._();

  static String generate(DdlTable table, SqlDialect dialect) {
    if (table.columns.isEmpty) return '';

    final String q = dialect.quoteChar;
    final StringBuffer sb = StringBuffer();

    sb.write('CREATE TABLE ');
    if (table.ifNotExists) {
      sb.write('IF NOT EXISTS ');
    }
    sb.write('${q}${table.name}$q (\n');

    final List<String> lines = <String>[];

    for (final DdlColumn col in table.columns) {
      lines.add('  ${_columnLine(col, dialect)}');
    }

    final List<String> pkColumns = table.columns
        .where((DdlColumn c) => c.primaryKey)
        .map((DdlColumn c) => '${q}${c.name}$q')
        .toList();

    if (pkColumns.length > 1) {
      lines.add('  PRIMARY KEY (${pkColumns.join(', ')})');
    }

    sb.write(lines.join(',\n'));
    sb.writeln();
    sb.write(')');

    if (dialect == SqlDialect.mysql) {
      sb.write(' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    }
    sb.write(';');

    if (table.indexes.isNotEmpty) {
      sb.writeln();
      sb.writeln();
      for (final DdlIndex idx in table.indexes) {
        final String idxSql = _indexSql(idx, table, dialect);
        if (idxSql.isNotEmpty) {
          sb.writeln(idxSql);
        }
      }
    }

    return sb.toString().trimRight();
  }

  static String _columnLine(DdlColumn col, SqlDialect dialect) {
    final String q = dialect.quoteChar;
    final StringBuffer sb = StringBuffer();

    sb.write('$q${col.name}$q ');
    sb.write(
      col.type.toSql(
        dialect,
        length: col.length,
        precision: col.precision,
        scale: col.scale,
      ),
    );

    if (col.autoIncrement) {
      switch (dialect) {
        case SqlDialect.postgres:
          sb.write(' GENERATED BY DEFAULT AS IDENTITY');
          break;
        case SqlDialect.mysql:
          sb.write(' AUTO_INCREMENT');
          break;
        case SqlDialect.sqlite:
          sb.write(' AUTOINCREMENT');
          break;
      }
    }

    if (col.primaryKey) {
      sb.write(' PRIMARY KEY');
    }

    if (col.notNull) {
      sb.write(' NOT NULL');
    }

    if (col.unique) {
      sb.write(' UNIQUE');
    }

    if (col.defaultValue != null && col.defaultValue!.trim().isNotEmpty) {
      sb.write(' DEFAULT ${_formatDefault(col)}');
    }

    return sb.toString();
  }

  static String _formatDefault(DdlColumn col) {
    final String raw = col.defaultValue!.trim();

    if (raw.toUpperCase() == 'NULL' ||
        raw.toUpperCase().startsWith('CURRENT_') ||
        raw.toUpperCase().startsWith('NOW(') ||
        raw == 'TRUE' ||
        raw == 'FALSE' ||
        raw.toUpperCase().startsWith('CURRENT_TIMESTAMP')) {
      return raw;
    }

    final bool isNumber = RegExp(r'^-?\d+(\.\d+)?$').hasMatch(raw);
    if (isNumber) return raw;

    if ((raw.startsWith("'") && raw.endsWith("'")) ||
        (raw.startsWith('"') && raw.endsWith('"'))) {
      return raw;
    }

    return "'${raw.replaceAll("'", "''")}'";
  }

  static String _indexSql(
      DdlIndex idx,
      DdlTable table,
      SqlDialect dialect,
      ) {
    if (idx.columnIds.isEmpty) return '';
    final String q = dialect.quoteChar;

    final List<String> cols = <String>[];
    for (final String colId in idx.columnIds) {
      final DdlColumn? col = _findColumn(table, colId);
      if (col != null && col.name.trim().isNotEmpty) {
        cols.add('$q${col.name}$q');
      }
    }

    if (cols.isEmpty) return '';

    final String uniqueKw = idx.unique ? 'UNIQUE ' : '';
    final String indexName =
    idx.name.trim().isEmpty ? 'idx_${table.name}_${cols.length}' : idx.name.trim();

    return 'CREATE ${uniqueKw}INDEX ${q}${indexName}$q '
        'ON $q${table.name}$q (${cols.join(', ')});';
  }

  static DdlColumn? _findColumn(DdlTable table, String colId) {
    for (final DdlColumn c in table.columns) {
      if (c.id == colId) return c;
    }
    return null;
  }
}

class QueryGenerator {
  QueryGenerator._();

  static String generate(QueryConfig config, SqlDialect dialect) {
    if (config.table.trim().isEmpty) return '';

    final String q = dialect.quoteChar;
    final StringBuffer sb = StringBuffer();

    sb.write('SELECT ');

    if (config.distinct) {
      sb.write('DISTINCT ');
    }

    final List<SelectColumn> activeCols =
    config.columns.where((SelectColumn c) => c.enabled && c.column.trim().isNotEmpty).toList();

    if (activeCols.isEmpty) {
      sb.write('*');
    } else {
      final List<String> colParts = activeCols.map((SelectColumn c) {
        final String colRef = _colRef(c.column, q);
        if (c.alias.trim().isEmpty) return colRef;
        return '$colRef AS ${q}${c.alias.trim()}$q';
      }).toList();
      sb.write(colParts.join(', '));
    }

    sb.write('\nFROM $q${config.table.trim()}$q');

    final List<WhereCondition> activeWhere = config.where
        .where((WhereCondition w) => w.enabled && w.column.trim().isNotEmpty)
        .toList();

    if (activeWhere.isNotEmpty) {
      sb.write('\nWHERE ');
      final List<String> parts = <String>[];
      for (int i = 0; i < activeWhere.length; i++) {
        final WhereCondition w = activeWhere[i];
        final String clause = _whereClause(w, q);
        if (clause.isEmpty) continue;
        if (parts.isEmpty) {
          parts.add(clause);
        } else {
          parts.add('${w.connector.upper} $clause');
        }
      }
      sb.write(parts.join('\n  '));
    }

    final List<String> activeGroupBy =
    config.groupBy.where((String g) => g.trim().isNotEmpty).toList();

    if (activeGroupBy.isNotEmpty) {
      final List<String> cols = activeGroupBy
          .map((String c) => _colRef(c, q))
          .toList();
      sb.write('\nGROUP BY ${cols.join(', ')}');
    }

    final List<OrderByClause> activeOrder = config.orderBy
        .where((OrderByClause o) => o.column.trim().isNotEmpty)
        .toList();

    if (activeOrder.isNotEmpty) {
      final List<String> parts = activeOrder.map((OrderByClause o) {
        return '${_colRef(o.column, q)} ${o.direction.upper}';
      }).toList();
      sb.write('\nORDER BY ${parts.join(', ')}');
    }

    if (config.limit != null && config.limit! > 0) {
      sb.write('\nLIMIT ${config.limit}');
    }

    if (config.offset != null && config.offset! > 0) {
      sb.write('\nOFFSET ${config.offset}');
    }

    sb.write(';');
    return sb.toString();
  }

  static String _colRef(String name, String q) {
    final String trimmed = name.trim();
    if (trimmed == '*') return '*';
    if (trimmed.contains('(') || trimmed.contains(' ')) return trimmed;
    return '$q$trimmed$q';
  }

  static String _whereClause(WhereCondition w, String q) {
    final String col = _colRef(w.column, q);
    final String op = w.operator.symbol;

    switch (w.operator) {
      case SqlOperator.isNull:
      case SqlOperator.isNotNull:
        return '$col $op';

      case SqlOperator.inList:
      case SqlOperator.notInList:
        final List<String> items = w.value
            .split(',')
            .map((String s) => s.trim())
            .where((String s) => s.isNotEmpty)
            .map((String s) => _literal(s))
            .toList();
        if (items.isEmpty) return '';
        return '$col $op (${items.join(', ')})';

      case SqlOperator.between:
        if (w.value.trim().isEmpty || w.value2.trim().isEmpty) return '';
        return '$col BETWEEN ${_literal(w.value.trim())} '
            'AND ${_literal(w.value2.trim())}';

      default:
        if (w.value.trim().isEmpty) return '';
        return '$col $op ${_literal(w.value.trim())}';
    }
  }

  static String _literal(String raw) {
    final String v = raw.trim();
    if (v.isEmpty) return "''";

    if (RegExp(r'^-?\d+(\.\d+)?$').hasMatch(v)) return v;

    if (v.toUpperCase() == 'NULL' ||
        v.toUpperCase() == 'TRUE' ||
        v.toUpperCase() == 'FALSE' ||
        v.toUpperCase().startsWith('CURRENT_') ||
        v.toUpperCase().startsWith('NOW(')) {
      return v;
    }

    if ((v.startsWith("'") && v.endsWith("'")) ||
        (v.startsWith('"') && v.endsWith('"'))) {
      return v;
    }

    return "'${v.replaceAll("'", "''")}'";
  }
}