import 'package:flutter/material.dart';

import 'sidebar_plugin.dart';

const List<SidebarPlugin> sidebarRegistry = <SidebarPlugin>[
  SidebarPlugin(
    id: 'cache_cleaner',
    group: SidebarGroup.fixed,
    icon: Icons.cleaning_services_rounded,
    labelKey: 'sidebar_cache_cleaner',
    defaultOrder: 0,
    canHide: false,
  ),
  SidebarPlugin(
    id: 'plugin_edit',
    group: SidebarGroup.fixed,
    icon: Icons.tune_rounded,
    labelKey: 'sidebar_plugin_edit',
    defaultOrder: 1,
    canHide: false,
  ),
  SidebarPlugin(
    id: 'downloads',
    group: SidebarGroup.fixed,
    icon: Icons.download_rounded,
    labelKey: 'sidebar_downloads',
    defaultOrder: 2,
    canHide: false,
  ),
  SidebarPlugin(
    id: 'deepseek',
    group: SidebarGroup.ai,
    icon: Icons.auto_awesome_rounded,
    labelKey: 'sidebar_deepseek',
    defaultOrder: 10,
    url: 'https://chat.deepseek.com',
  ),
  SidebarPlugin(
    id: 'gemini',
    group: SidebarGroup.ai,
    icon: Icons.auto_awesome_outlined,
    labelKey: 'sidebar_gemini',
    defaultOrder: 11,
    url: 'https://gemini.google.com',
  ),
  SidebarPlugin(
    id: 'chatgpt',
    group: SidebarGroup.ai,
    icon: Icons.chat_bubble_outline_rounded,
    labelKey: 'sidebar_chatgpt',
    defaultOrder: 12,
    url: 'https://chat.openai.com',
  ),
  SidebarPlugin(
    id: 'claude',
    group: SidebarGroup.ai,
    icon: Icons.psychology_outlined,
    labelKey: 'sidebar_claude',
    defaultOrder: 13,
    url: 'https://claude.ai',
  ),
  SidebarPlugin(
    id: 'meta_ai',
    group: SidebarGroup.ai,
    icon: Icons.blur_on_rounded,
    labelKey: 'sidebar_meta_ai',
    defaultOrder: 14,
    url: 'https://www.meta.ai',
  ),
  SidebarPlugin(
    id: 'telegram',
    group: SidebarGroup.social,
    icon: Icons.send_rounded,
    labelKey: 'sidebar_telegram',
    defaultOrder: 20,
    url: 'https://web.telegram.org',
  ),
  SidebarPlugin(
    id: 'whatsapp',
    group: SidebarGroup.social,
    icon: Icons.chat_rounded,
    labelKey: 'sidebar_whatsapp',
    defaultOrder: 21,
    url: 'https://web.whatsapp.com',
  ),
  SidebarPlugin(
    id: 'github',
    group: SidebarGroup.social,
    icon: Icons.code_rounded,
    labelKey: 'sidebar_github',
    defaultOrder: 22,
    url: 'https://github.com',
  ),
  SidebarPlugin(
    id: 'google_drive',
    group: SidebarGroup.cloud,
    icon: Icons.add_to_drive_rounded,
    labelKey: 'sidebar_google_drive',
    defaultOrder: 30,
    url: 'https://drive.google.com',
  ),
  SidebarPlugin(
    id: 'terra_box',
    group: SidebarGroup.cloud,
    icon: Icons.cloud_rounded,
    labelKey: 'sidebar_terra_box',
    defaultOrder: 31,
    url: 'https://www.terrabox.com',
  ),
  SidebarPlugin(
    id: 'settings',
    group: SidebarGroup.fixed,
    icon: Icons.settings_outlined,
    labelKey: 'sidebar_settings',
    defaultOrder: 999,
    canHide: false,
    pinnedBottom: true,
  ),
];